-   id: kustomize
    name: kustomize (via system)
    description: kustomize
    entry: kustomize build
    language: system
    args: [overlay/production]
    always_run: true
    pass_filenames: false
    
